language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - npm run build
  - ls build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: iamleonid
  acl: public_read
  local_dir: build
  skip_cleanup: true
branches:
  only:
    - master