language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm run build
- ls build
deploy:
  provider: s3
  access_key_id: AKIASSYM3Q5YYQV6LLHG
  secret_access_key:
    secure: oZ22DriPXDA+QRsyKZCuZoKRumFvv50+xUibICLyhF5aKXQCSkWykB2oFwuh2vwOPGNCGyIlAxUSVq6WlmmC34wrEPIiSopj9T5L9Ui/IhxLBbuG/FUuMHj5jufvDa858AdMpsZcjXKZSzwp5UAEqBM3t48aHup7NskAb3zUzhxa7Hm8XR2/z6bTd271+hAg7ObygxjsWa1yeDFYudX5THJER8mhW3gN3dmLM0XPaVAnH53cBJT3qfdYCRR7BOu8Si1C7m4os2u3huipw2DLIAiDrg7nnPqQbVNnH/AXViTVJ0iDiWNsTIP+tnorUUZp6Ga6KYd1NGYLraSSWdX53iBVKDkq1ntANLgReTXd7tLyi6wQMlFKkQleNvNW5IM/JQcxfnNBrbL3nMBJscNNddFS11XwGu6nXPIqxPh0yO/J8LFmpXS6r+DG7AhsoGyBtiT5WmuHzJ1vFR2TPbfVHbShBGZ0qy7sps3BdsZ15fBwsoQmyW6cdba6kD64XNdfJ1QWlwoDRZbHctNJw/ck4ef7+2ATdIouaEcHSrRUOSOB43xxVtn2ujqn1iGWxqgQWhw3b73f9K+ng9kpKL9m3/rzTux21ipEH77DeWH1KwkjuX4mF7fTx7zIUheO0+w0eum+4AHfoD/Gs3Q5H+AMRsaHSIRtfscOgBootcaTgOE=
  bucket: iamleonid
  acl: public_read
  local_dir: build
  skip_cleanup: true
branches:
  only:
  - master
